[build]
  # We specify the build command which will install dependencies using the default Python version
  command = "pip install -r functions/get-video-link/requirements.txt"
  functions = "functions"
  
[functions]
  directory = "functions"

# Netlify ko force karna ki woh default environment use kare, mise ko ignore kare
[functions."*"]
  python_runtime = "python3.10.12"

