[build]
  # Functions directory jahan python libraries install hongi
  functions = "functions"
  # Dependencies install karne ki command
  command = "pip install -r functions/get-video-link/requirements.txt"
  
[functions]
  # Functions ka folder structure

  directory = "functions"
# Yahi woh setting hai jo initializing ko control karti hai
[functions."*"]
  # Hum Python 3.8 specify kar rahe hain
  python_runtime = "python3.10.12"
